### ISSUE TITLE
Meeting 3/13/19

### ISSUE THREAD

**Issue by g-simmons** [quadcopter-ar/QuadcopterAR#23]
### Localization:
- [ ] Fix discrepancy between ORB-SLAM coordinate axes and scale and quadcopter coordinate axes and scale.
- Stereo camera manufacturer has still not responded
- [x] Verify that we can run multiple ORB-SLAM instances on one workstation

### Gaming:
- [ ] Get code and documentation for communication from ROS to Unity implemented by Jim
  - @JCBreath 
- [ ] Publish most recent game version to GitHub
  - @JCBreath 
- [ ] Modify maze game to allow xbox controller input
  - @XanderFang @bjson
- [ ] Set up virtual camera in simulation
  - Camera information from Gazebo can now be viewed in ROS
  - Forwarding this camera information to Unity is on hold while we work in 2-player simulation. 

### Overall:
- **Room reservation for video test has been made for March 17**
- [ ] Measure system delays
- [ ] Upload weidong's barrel distortion correction project to this repo
  - [ ] Transfer ownership from @liaoyg 
- [ ] Remove @songyul2 from repo
  - @mind111 
- [ ] Install ardupilot master on the other quadcopters
  - @g-simmons 

## This week

# Task tracking has been moved to organization projects.
