### ISSUE TITLE
Testing Checklist 3/17/19

### ISSUE THREAD

**Issue by g-simmons** [quadcopter-ar/QuadcopterAR#24]
Before:

- [x] Ordered more rotors for the quadcopters
- [x] Install master on additional quadcopters
   Solos 1 and 3 are now running master. 2 hangs on startup, saving troubleshooting this for later.

- [ ] Verify ORB-SLAM scaling and orientation

- [ ] Test connecting to two drones simultaneously from the Linux workstation

Day of:

- 3 Solos with enough blades for 2 simultaneous flight
- 3 Solo controllers
- Solo controller chargers
- Solo rotor guards
- Solo extra batteries
- Solo battery chargers

- 2 GoPros
- GoPro extra batteries and chargers

- 3 Workstations
- Networking - router & ethernet cables

- Oculus stuff

- Wall markers 

- Tether and anchor for first flight test

- Equipment to record first-person view, third person drone and player, close up of controller.
